### PR TITLE
Coding style modifications

### PR DESCRIPTION
**Pull request by samuelmacedo83**
Hi @leeper ,

I've made some modification in the code, just to put in the [style](http://cloudyr.github.io/styleguide/).
I also rewrite signature_v4() using %>% operators.

### CODE REVIEW

**Comment by samuelmacedo83** [comment]
Ok @leeper , I'll modify.

**Comment by leeper** [comment]
I guess I'd also say, were I going to keep maintaining it, that there's zero advantage to writing package code with pipes (due to the added dependency, performance loss, and added code ambiguity). But I'll leave it to you.

**Comment by samuelmacedo83** [comment]
I'll take that under advisement.  Thank you for your input and the opportunity.

**Comment by samuelmacedo83** [comment]
hi @leeper, do you have any more comments on the code?
I'm sure you are busy, but I'd like to understand and establish how this project will work. I don't have write access yet, so do you plan on reviewing and merging my PR's?
I think the project would progress faster if I had permission to merge, but I understand if you think differently.
Let me know your thoughts.

**Comment by jon-mago** [comment]
Hi @samuelmacedo83 

Thanks for your work on this.  I don't feel like it's worth adding the magrittr library for the sake of one function in a low-level package like this - especially as the `aws.signature` package doesn't really have any 'pipe-able' functions that it exposes.

**Comment by jmorten** [comment]
can this be closed?

**Pull request closed without merging**
